#!/usr/bin/env python3
"""Ejemplo práctico de uso del cliente de Supabase.

Este script muestra cómo:
1. Conectarse a Supabase
2. Insertar datos
3. Consultar datos
4. Actualizar datos
5. Eliminar datos
"""

from supabase_client import get_supabase_client

def ejemplo_basico():
    """Ejemplo básico de operaciones CRUD."""

    try:
        client = get_supabase_client()
        print("✅ Conexión a Supabase exitosa\n")

        # PASO 1: Consultar datos existentes
        print("📖 1. Consultando datos...")
        try:
            datos = client.select('usuarios', limit=10)
            print(f"   ✓ Se encontraron {len(datos)} registros")
            for usuario in datos:
                print(f"   - {usuario}")
        except Exception as e:
            print(f"   ⚠️ No se pudo consultar (tabla puede no existir): {e}")

        # PASO 2: Insertar un nuevo usuario
        print("\n✍️ 2. Insertando nuevo usuario...")
        try:
            nuevo_usuario = {
                'nombre': 'Juan Pérez',
                'email': 'juan@example.com'
            }
            resultado = client.insert('usuarios', nuevo_usuario)
            print(f"   ✓ Usuario insertado: {resultado}")
        except Exception as e:
            print(f"   ⚠️ No se pudo insertar: {e}")

        # PASO 3: Actualizar datos
        print("\n🔄 3. Actualizando usuario...")
        try:
            cliente.update(
                'usuarios',
                {'nombre': 'Juan Carlos Pérez'},
                {'email': 'juan@example.com'}
            )
            print("   ✓ Usuario actualizado")
        except Exception as e:
            print(f"   ⚠️ No se pudo actualizar: {e}")

        # PASO 4: Eliminar datos
        print("\n🗑️  4. Eliminando usuario...")
        try:
            client.delete('usuarios', {'email': 'juan@example.com'})
            print("   ✓ Usuario eliminado")
        except Exception as e:
            print(f"   ⚠️ No se pudo eliminar: {e}")

        print("\n✨ Ejemplo completado")

    except Exception as e:
        print(f"❌ Error: {e}")


def crear_tabla_ejemplo():
    """Código SQL para crear una tabla de ejemplo.

    Ejecuta esto en el dashboard de Supabase → SQL Editor
    """
    sql = """
    -- Crear tabla de usuarios
    CREATE TABLE usuarios (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      nombre TEXT NOT NULL,
      email TEXT UNIQUE NOT NULL,
      edad INT,
      ciudad TEXT,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    );

    -- Permitir lectura pública (anon)
    ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
    CREATE POLICY "Allow public read" ON usuarios FOR SELECT USING (true);
    CREATE POLICY "Allow public insert" ON usuarios FOR INSERT WITH CHECK (true);
    CREATE POLICY "Allow public update" ON usuarios FOR UPDATE USING (true);
    CREATE POLICY "Allow public delete" ON usuarios FOR DELETE USING (true);
    """

    print("📋 Código SQL para crear tabla en Supabase:")
    print("=" * 60)
    print(sql)
    print("=" * 60)
    print("\n1. Ve a: https://app.supabase.com")
    print("2. Selecciona tu proyecto")
    print("3. SQL Editor → New Query")
    print("4. Copia y pega el código anterior")
    print("5. Click en 'Run'")


if __name__ == "__main__":
    print("🚀 Ejemplos de Supabase\n")

    crear_tabla_ejemplo()

    print("\n" + "=" * 60)
    print("Ejecutando ejemplo CRUD...")
    print("=" * 60)

    # Descomenta la siguiente línea para ejecutar el ejemplo
    # ejemplo_basico()

    print("\n💡 Próximos pasos:")
    print("1. Crea la tabla usando el SQL anterior")
    print("2. Descomenta ejemplo_basico() en este archivo")
    print("3. Ejecuta: python ejemplo_supabase.py")
