// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaTickets.Infrastructure.Data;

#nullable disable

namespace SistemaTickets.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaTickets.Domain.Entities.Cliente", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<bool>("Activo").HasColumnType("bit");
                b.Property<string>("Correo").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Empresa").HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime2");
                b.Property<string>("Nombre").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<string>("Telefono").HasMaxLength(50).HasColumnType("nvarchar(50)");

                b.HasKey("Id");
                b.ToTable("Clientes");
            });

            modelBuilder.Entity("SistemaTickets.Domain.Entities.Ticket", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int?>("AsignadoAId").HasColumnType("int");
                b.Property<int>("ClienteId").HasColumnType("int");
                b.Property<int>("CreadoPorId").HasColumnType("int");
                b.Property<string>("Descripcion").IsRequired().HasMaxLength(4000).HasColumnType("nvarchar(4000)");
                b.Property<int>("Estado").HasColumnType("int");
                b.Property<DateTime?>("FechaCierre").HasColumnType("datetime2");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime2");
                b.Property<int>("Prioridad").HasColumnType("int");
                b.Property<string>("Titulo").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");

                b.HasKey("Id");
                b.HasIndex("AsignadoAId");
                b.HasIndex("ClienteId");
                b.HasIndex("CreadoPorId");
                b.ToTable("Tickets");
            });

            modelBuilder.Entity("SistemaTickets.Domain.Entities.TicketSeguimiento", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Comentario").IsRequired().HasMaxLength(4000).HasColumnType("nvarchar(4000)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime2");
                b.Property<int>("TicketId").HasColumnType("int");
                b.Property<int>("UsuarioId").HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("TicketId");
                b.HasIndex("UsuarioId");
                b.ToTable("TicketSeguimientos");
            });

            modelBuilder.Entity("SistemaTickets.Domain.Entities.Usuario", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<bool>("Activo").HasColumnType("bit");
                b.Property<string>("Correo").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime2");
                b.Property<string>("Nombre").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<int>("Rol").HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("Correo").IsUnique();
                b.ToTable("Usuarios");
            });

            modelBuilder.Entity("SistemaTickets.Domain.Entities.Ticket", b =>
            {
                b.HasOne("SistemaTickets.Domain.Entities.Cliente", "Cliente")
                    .WithMany("Tickets")
                    .HasForeignKey("ClienteId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SistemaTickets.Domain.Entities.Usuario", "AsignadoA")
                    .WithMany("TicketsAsignados")
                    .HasForeignKey("AsignadoAId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("SistemaTickets.Domain.Entities.Usuario", "CreadoPor")
                    .WithMany("TicketsCreados")
                    .HasForeignKey("CreadoPorId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("AsignadoA");
                b.Navigation("Cliente");
                b.Navigation("CreadoPor");
            });

            modelBuilder.Entity("SistemaTickets.Domain.Entities.TicketSeguimiento", b =>
            {
                b.HasOne("SistemaTickets.Domain.Entities.Ticket", "Ticket")
                    .WithMany("Seguimientos")
                    .HasForeignKey("TicketId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("SistemaTickets.Domain.Entities.Usuario", "Usuario")
                    .WithMany("Seguimientos")
                    .HasForeignKey("UsuarioId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Ticket");
                b.Navigation("Usuario");
            });

            modelBuilder.Entity("SistemaTickets.Domain.Entities.Cliente", b =>
            {
                b.Navigation("Tickets");
            });

            modelBuilder.Entity("SistemaTickets.Domain.Entities.Ticket", b =>
            {
                b.Navigation("Seguimientos");
            });

            modelBuilder.Entity("SistemaTickets.Domain.Entities.Usuario", b =>
            {
                b.Navigation("Seguimientos");
                b.Navigation("TicketsAsignados");
                b.Navigation("TicketsCreados");
            });
#pragma warning restore 612, 618
        }
    }
}
